### ISSUE TITLE
Problems with generating prisma client using bun

### ISSUE THREAD

**Issue by Elijjahh** [prisma/nuxt-prisma#47]
## The problem
When I install @prisma/nuxt and start at dev mode everything works until "Generating Prisma client...". At this moment it just freezes and nothing happens

## Steps to reproduce:

```
# creating nuxt project
bunx nuxi@latest init <my-app>

bun install @prisma/nuxt
```

Add "@prisma/nuxt" to nuxt modules and run:
```
bun run dev
```

## What I've noticed
There are some experiments that I've done. I've noticed that it works when there is no bun.lockb. So I tried installing packages and start dev mode with deleted bun.lockb and it worked.

Also if I add bunfig.toml:
```
[install.lockfile]

# whether to save the lockfile to disk
save = false
```
then it also works.

Also after successful first time (using no bun.lockdb or bunfig.toml)  it works anyway (with/without bun.lockdb). I am new to bun and prisma so I don't know the exact reason. I guess that "@prisma/nuxt" installs "@prisma/client" at first time and that breaks everything and at second time it is already installed so everything works. And it's very strange that bun.lockdb somehow affects runtime

## Screenshots
Generation freezes. You can see that it started at 22:03 and I made a screenshot at 22:06:

![изображение](https://github.com/user-attachments/assets/54ce2d39-49dc-4f50-a38c-ade311f47815)

Generation works good. Removed @prisma/nuxt from modules so it doesn't run at nuxt prepare. Then removed bun.lockdb and ran bun dev:

<img width="1440" alt="Снимок экрана 2024-11-01 в 22 12 12" src="https://github.com/user-attachments/assets/485dfd34-89d0-40a1-bd98-ea475f891d76">
<img width="1440" alt="Снимок экрана 2024-11-01 в 22 13 33" src="https://github.com/user-attachments/assets/6512a1d7-eeac-4c46-b697-3f464afc0c76">

Generation works. Added bunfig.toml

<img width="1440" alt="Снимок экрана 2024-11-01 в 22 17 11" src="https://github.com/user-attachments/assets/ce323ba9-e090-4167-8c68-f3c96c1f2be8">

**Comment by Jarred-Sumner** [comment]
I think this is a bug in Bun

**Comment by Elijjahh** [comment]
> I think this is a bug in Bun

So should I create an issue at their repo?

**Comment by Elijjahh** [comment]
> I think this is a bug in Bun

Okay, then I'll create an issue at it's repo

**Comment by naruko-hstk** [comment]
Don't use Bun.
Use Yarn instead.

**Comment by abunaum** [comment]
same problem, stuck in "generating prisma client" when run "bunx nuxi@latest module add prisma"

**Comment by ankur-arch** [comment]
Thanks for reporting the issue @Elijjahh. 

> same problem, stuck in "generating prisma client" when run "bunx nuxi@latest module add prisma"


Can you enable [debug logging](https://www.prisma.io/docs/orm/prisma-client/debugging-and-troubleshooting/debugging#setting-the-debug-environment-variable) and give me the output?

**Comment by BlueBazze** [comment]
![image](https://github.com/user-attachments/assets/e5f648a3-8da2-42be-a7f3-894c261a9ebc)
Ran into the same problem with a fresh project using bun.
It logs nothing after 10 mins, escaping the process dont give anything either.
Manually running `bunx prisma generate` seems to work just fine.
![image](https://github.com/user-attachments/assets/00ae149d-ba4d-4891-99cc-b52e90b28c12)

**Comment by Elijjahh** [comment]
> Can you enable [debug logging](https://www.prisma.io/docs/orm/prisma-client/debugging-and-troubleshooting/debugging#setting-the-debug-environment-variable) and give me the output?

@ankur-arch here is the output:

![изображение](https://github.com/user-attachments/assets/18f68019-0672-4db0-b0ff-59de125e8bb0)

**Comment by ankur-arch** [comment]
> P.S: When there will be an update for npm package? I see you merged some fixes at main branch but there is no release yet

Yep, I'll be releasing the fixes soon!

**Comment by itsmelouis** [comment]
Hello! Any news about the bug?

**Comment by ankur-arch** [comment]
Hey @itsmelouis , I'll provide updates here as I release a fix for this.

**Comment by itsmelouis** [comment]
Nice, thanks for the answer! :)

**Comment by tanayvk** [comment]
In the meanwhile, to get things working with bun, what worked for me is:

I edited `node_modules/@prisma/nuxt/dist/module.mjs` and commented out the following code inside the `generateClient` function.

```
  // if (installPrismaClient) {
  //   try {
  //     const installCmd = installingPrismaClientWithPM();
  //     await execa(installCmd.pm, installCmd.command, {
  //       cwd: directory
  //     });
  //   } catch (error) {
  //     logError(
  //       PREDEFINED_LOG_MESSAGES.generatePrismaClient.prismaClientInstallationError
  //     );
  //   }
  // }
```

The code just tries to run `bun add @prisma/client --dev` so I ran that manually instead.

**Comment by davidparys** [comment]
> In the meanwhile, to get things working with bun, what worked for me is:
> 
> I edited `node_modules/@prisma/nuxt/dist/module.mjs` and commented out the following code inside the `generateClient` function.
> 
> ```
>   // if (installPrismaClient) {
>   //   try {
>   //     const installCmd = installingPrismaClientWithPM();
>   //     await execa(installCmd.pm, installCmd.command, {
>   //       cwd: directory
>   //     });
>   //   } catch (error) {
>   //     logError(
>   //       PREDEFINED_LOG_MESSAGES.generatePrismaClient.prismaClientInstallationError
>   //     );
>   //   }
>   // }
> ```
> 
> The code just tries to run `bun add @prisma/client --dev` so I ran that manually instead.

```typescript
// nuxt-config.ts
  prisma: {
    autoSetupPrisma: false,
    installClient: false,
    installStudio: false
  },
 ```
 
 ```CLI
Nuxt 3.14.159 with Nitro 2.10.4                                                                                                                                                                                                                                11:13:52 PM
ℹ Using zod with vee-validate                                                                                                                                                                                                                                 11:13:54 PM
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css                                                                                                                                                                                          nuxt:tailwindcss 11:13:54 PM
✔ Prisma CLI is already installed.                                                                                                                                                                                                                            11:13:55 PM
✔ Prisma schema file exists.                                                                                                                                                                                                                                  11:13:55 PM
✔ Database migrations folder exists.                                                                                                                                                                                                                          11:13:55 PM
                                                                                                                                                                                                                                                               11:13:55 PM
Not migrating the database.
Generating Prisma client...                                                                                                                                                                                                                                    11:13:55 PM

                                                                                                                                                                                                                                                               11:13:56 PM
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.22.0) to ./node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client in 34ms

Skipped installing Prisma Studio.                                       
```

**Comment by Elijjahh** [comment]
For anyone with the same problem upgrading bun to 1.1.38 fixed it! I didn't try to test with versions between 1.1.33 and 1.1.38 so may be bug was fixed earlier. For me it doesnt matter) So I am closing this issue

**Comment by Elijjahh** [comment]
@ankur-arch thanks for your care

**Comment by Kuuzoo** [comment]
> For anyone with the same problem upgrading bun to 1.1.38 fixed it! I didn't try to test with versions between 1.1.33 and 1.1.38 so may be bug was fixed earlier. For me it doesnt matter) So I am closing this issue

I've been trying it with every single version in that ratio, including 1.1.38 and I'm still experiencing the same...
Maybe somebody else can say if 1.1.38 fixes this for them?

**Comment by Chew** [comment]
Still seems to occur on 1.1.38 (unless I do @davidparys's workaround, which worked before)
