### ISSUE TITLE
Incompatibility with Prisma ORM 6

### ISSUE THREAD

**Issue by jamols09** [prisma/nuxt-prisma#67]
As of the moment I cannot find a way to fix the issue. When you install this module you will get `PrismaClient is not a constructor` which will cause the developer tool not to show and causes some weird behavior with Nuxt.

![image](https://github.com/user-attachments/assets/15539751-7dd5-4102-a11b-7f65b47dd62e)

**Comment by damisparks** [comment]
@jamols09 I am not a massive fan of the `nuxt-prisma` package. The issue you've opened needs more information. 
In the future, I encourage you to imagine yourself as the maintainer before opening an issue. 
Could you share a reproduction repo or example?

**Comment by ankur-arch** [comment]
Thanks @jamols09 for creating the issue. 

@damisparks is right here, I need more information to reproduce this issue.

**Comment by tinegaCollins** [comment]
revert to these version till the issue is fixed    "@prisma/client": "^5.22.0",     "@prisma/nuxt": "^0.0.35", 
it worked for me

**Comment by jharrell** [comment]
@tinegaCollins were you also experiencing this issue? Could you provide a repo to help us debug this?

**Comment by Lateralus58** [comment]
experiencing the same issue on a fresh install of nuxt v3.14.1592

Steps to reproduce:
- create clean nuxt project `npx nuxi@latest init <my-app>`
- install @prisma/nuxt `npm install @prisma/nuxt`
- add `@prisma/nuxt` to nuxt.config.ts as module
- start dev server `npx run dev`
- select prisma console defaults
- open browser `https://localhost:3000' and view DevTools console

**Comment by RomainRoth** [comment]
Hi @jharrell , @ankur-arch 

Here's a repository reproducing the issue : [repo link](https://github.com/RomainRoth/prisma-nuxt-failure)

With prisma/client 5.22.0 & prisma/nuxt 0.0.35 no issues
With prisma/client 6.0.1 & prisma/nuxt 0.1.13 we get error messages within the browser console, also happens in storybook but w/e

I've migrated between the two versions so you can check the differences : 
[commits](https://github.com/RomainRoth/prisma-nuxt-failure/commits/main/)

In this large commit, you can see all the changes that been made to the generated prisma client between the two versions :
[commit](https://github.com/RomainRoth/prisma-nuxt-failure/commit/00fd3091d260f9bee0f0ed1bfc3252ed1835ba39)

**Comment by RomainRoth** [comment]
Just for reference, on this repo :

No issues directly with npx prisma generate, but fails at npm run build / nuxt build

```
PS E:\GitHub\prisma-nuxt-failure> npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Installed the @prisma/client and prisma packages in your project

✔ Generated Prisma Client (v6.0.1) to .\node_modules\@prisma\client in 40ms

Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)

Tip: Want to react to database changes in your app as they happen? Discover how with Pulse: https://pris.ly/tip-1-pulse

PS E:\GitHub\prisma-nuxt-failure> npm run build      

> build
> nuxt build

Nuxt 3.14.1592 with Nitro 2.10.4                                                                                                                                                                                      
✔ Prisma CLI is already installed.                                                                                                                                                                                   
✔ Prisma schema file exists.                                                                                                                                                                                         
✔ Database migrations folder exists.                                                                                                                                                                                 

Not migrating the database.
Generating Prisma client...                                                                                                                                                                                           

 ERROR  ✘ Failed to generate Prisma Client.   
```

**Comment by tinegaCollins** [comment]
@jharrell this issue started when we update a repo packages

**Comment by tinegaCollins** [comment]
@jharrell  can I trust you with a private repo?

**Comment by jharrell** [comment]
Yes, you can reach me at my Prisma email: Harrell (at) Prisma (dot) io

**Comment by guarenty** [comment]
same issue here, using @prisma/nuxt@0.1.2 until this is resolved

**Comment by tixlag** [comment]
Same issue.  As a temporary solution, I downgraded @prisma/client from 6.0.1 to 5.22.0

It work for me:
"@prisma/client": "5.22.0",
"@prisma/nuxt": "0.1.3",

**Comment by gsxdsm** [comment]
Same issue. Sigh.

**Comment by jharrell** [comment]
Hi @gsxdsm if you downgrade to Prisma Client `5.22.0` is the problem resolved?

**Comment by gsxdsm** [comment]
Will try, but I'd like to be on 6.1. Not sure why nuxt-prisma is stuck on an older version of Prisma. Doesn't make sense.

**Comment by pirhoo** [comment]
Prisma 6 is only 3 weeks old, so I guess we need to be patient and give a break to opensource maintainers that already give a lot to the community.

**Comment by Qualterink** [comment]
sam issue, downgrade works fine

**Comment by ankur-arch** [comment]
Thanks for the patience on this everyone 🙏 . 

I can't reproduce the error with `0.0.0-experimental-b764aa7` and this PR should resolve this https://github.com/prisma/nuxt-prisma/pull/69.

Just be sure to use the required node versions required for [Prisma 6 too](https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-6). 

<img width="865" alt="image" src="https://github.com/user-attachments/assets/a63e5155-b41a-4d1c-9fa5-9113419372f1" />

**Comment by goldengecko** [comment]
Another data point: problem occurred with 6.1.0. I realised I had installed it using node 22.2.0, so I updated to node 22.12.0 and did a clean reinstall. Problem still occurred. Downgraded to Prisma 5.22.0 as described above and the problem disappeared.

**Comment by ankur-arch** [comment]
@goldengecko 👋 , can you check if this is resolved in the pre-release version? `0.0.0-experimental-b764aa7`.

The package wasn't published as there weren't significant changes 😕  from the PR above.

**Comment by goldengecko** [comment]
@ankur-arch Yes, I can confirm that it works with the following settings in node 22.12.0:

    "@prisma/nuxt": "0.0.0-experimental-b764aa7",
    "@prisma/client": "^6.1.0",
    "prisma": "^6.1.0"

though I do get some errors about missing fonts in the Prisma Studio instance it boots up:

GET http://localhost:5555/inter-latin-400-normal.27ae72da.woff2 net::ERR_ABORTED 404 (Not Found)Understand this errorAI
index.css:1 
        
GET http://localhost:5555/inter-all-400-normal.4c1f8a0d.woff 404 (Not Found)Understand this errorAI
index.js:1 Bootstrap Duration: 324.786865234375 ms
index.css:1 
        
GET http://localhost:5555/inter-latin-600-normal.87d718a2.woff2 net::ERR_ABORTED 404 (Not Found)Understand this errorAI
index.css:1 
        
GET http://localhost:5555/jetbrains-mono-latin-400-normal.80a5dc9e.woff2 net::ERR_ABORTED 404 (Not Found)Understand this errorAI
index.css:1 
        
GET http://localhost:5555/inter-all-600-normal.d0a7c8a9.woff net::ERR_ABORTED 404 (Not Found)Understand this errorAI
index.css:1 
        
GET http://localhost:5555/jetbrains-mono-all-400-normal.f86807b7.woff net::ERR_ABORTED 404 (Not Found)


Thanks for getting this working

**Comment by jharrell** [comment]
@NyllRE Thanks for the report! Would you mind opening up a new issue with a reproduction? We've gotten reports that this was fixed with a previous version, so there might be a different underlying issue here 😄

**Comment by tixlag** [comment]
@prisma/nuxt:0.3.0

![Image](https://github.com/user-attachments/assets/ea20f7f5-b60e-4dd6-9c34-451de9cea763)
